# The master meme list: per world, (rarity, id, name, form, icon, museum description).
# form = Statue | Painting | Coin | Tablet | Relic. Edit here, then run gen_meme_list.py.
# (rarity, id, name, form, icon, description)  form: Statue | Painting | Coin | Tablet | Relic
W = {}
W[1] = [
("Basic","DaWaeEchidna","Da Wae Red Echidna","Statue","🔴","A stubby red echidna that always knew the way. Nobody else did."),
("Basic","SeaShantyMug","Sea Shanty Mug","Relic","🍺","Soon may the Wellerman come. A whole internet sang along in 2021."),
("Basic","AisleYodelSet","Aisle Yodel Cowboy Set","Relic","🤠","A tiny hat and boots left in a store aisle. The yodel still echoes."),
("Basic","ConvinceMeTable","Convince Me Otherwise Table","Relic","💺","A folding table where humans argued with strangers. Nobody's mind was changed."),
("Common","ShockedRodent","Shocked Yellow Rodent","Statue","😮","Frozen forever with its mouth wide open. Used whenever anyone acted surprised."),
("Common","IsThisABird","Is This a Bird?","Painting","🦋","A man points at a butterfly and asks the wrong question. A human classic."),
("Common","ChonkyBunny","Chonky Gray Bunny","Statue","🐰","A rabbit of truly legendary size. Humans simply called it big."),
("Common","SpicyLasagna","Spicy Lasagna Diss Track","Relic","🍝","A lasagna with a record baked into it. The spiciest dish of the 2010s."),
("Uncommon","SpikedShellCrown","Spiked Shell Crown","Relic","👑","A green spiked shell wearing a crown. The internet argued about it for a week."),
("Uncommon","GrapeSurgery","Grape Operation Theater","Relic","🍇","They did surgery on a grape. The grape survived."),
("Uncommon","BadBoyHatchback","This Bad Boy Hatchback","Statue","🚙","You can fit so many memes in this bad boy."),
("Uncommon","TempleTap","Think-About-It Temple Tap","Statue","🤔","Can't fail your test if you never take it. Pure genius."),
("Rare","SteamedClams","Steamed Clams at Noon Platter","Relic","🍔","A platter of burgers and an aurora in the kitchen. Localized entirely within it."),
("Rare","MegaSealTape","Mega Seal Tape","Relic","🚣","Held a sawn-in-half boat together. The water stayed in."),
("Rare","PurpleTitanBuggy","Purple Titan Buggy","Statue","🚗","A giant purple conqueror's tiny car. He could snap his fingers but still drove this."),
("Rare","OrcaRebellionBoat","Orca Rebellion Boat","Statue","🐋","The orcas started sinking boats in 2023. The internet picked a side."),
("Epic","NeverMissDartboard","Never-Miss Dartboard","Relic","🎯","Hit or miss? It never misses, huh."),
("Epic","CrimeTownBoss","Crime Town Big Boss","Statue","🤵","That's how crime works. Learned from a thousand phone ads."),
("Legendary","BoneComedian","Bone Comedian Fighter","Statue","💀","A grinning skeleton who crashed the biggest fighting game party. Bad time guaranteed."),
("Legendary","SugarSneakJohnny","Sugar-Sneak Johnny","Statue","🍬","Eating sugar? No, papa. Open your mouth. Ha ha ha."),
]
W[2] = [
("Basic","FrostFlask","Sksksk Frost Flask","Relic","🧴","Covered in stickers and scrunchies. And I oop."),
("Basic","BreathtakingCyberGuy","You're Breathtaking Cyber-Guy","Statue","🤖","Pointed at a crowd and told them they were breathtaking. They were."),
("Basic","EnslavedMoisture","Enslaved Moisture Cubes","Relic","❄️","Ice: water in chains. Free them."),
("Common","StonksHead","Stonks Suit Head","Statue","📈","A smooth head that understood the market perfectly. Stonks only go up."),
("Common","AhShucks","Ah Shucks, Here We Go Again","Statue","🚲","Every human's reaction to Monday. Here we go again."),
("Common","UncannyHedgehog","Uncanny Blue Speedy Hedgehog","Statue","🦔","The redesign so scary they redesigned it again."),
("Uncommon","SpaceInfant","Green Space Infant","Statue","👶","A tiny green baby with enormous ears. Every human wanted to protect it."),
("Uncommon","MeAndTheCrew","Me and the Crew","Statue","👬","Four friends walking toward adventure. Or the snack aisle."),
("Uncommon","CyberWedgeTruck","Cyber Wedge Truck","Statue","🚚","An unbreakable window demo. The window broke."),
("Rare","YelledAtCat","Yelled-At Dinner Cat","Statue","🐱","A confused cat at dinner, being yelled at. It did nothing wrong."),
("Rare","RaidAlien","Arms-Back Raid Alien","Statue","🛸","They can't stop all of us. They stopped all of us."),
("Rare","AngelWingDancer","Angel-Wing Dance Legend","Statue","🕺","A dance so powerful it gained wings."),
("Epic","KombuchaDisgust","Kombucha Disgust Bottle","Relic","🍾","One sip made the whole internet scrunch its face."),
("Epic","DoubleTakeBlink","Double-Take Blink Bust","Statue","😳","Blinked in disbelief. Humans have been blinking back ever since."),
("Epic","TallPinkPiglet","Absurdly Tall Pink Piglet","Statue","🐷","Scientists calculated her real height. They regret it."),
("Legendary","SpongeLeaving","Yellow Porous Sponge Leavin'","Statue","🧽","Aight, imma head out. The most famous exit in history."),
("Legendary","CappuccinoBallerina","Cappuccino Ballerina","Statue","☕","Half dancer, half coffee cup. Pirouettes until the foam spills."),
("Exotic","FrozenCoffinDance","Frozen Coffin Dance Crew","Statue","⚰️","They danced the dead to the grave. On ice."),
("Mythical","HundredMenGorilla","100 Men vs 1 Gorilla","Statue","🦍","Who would win? The internet argued for a whole month."),
("Uncommon","GothDanceHands","Goth Dance Freeze","Statue","🖤","The jerky goth dance everyone copied at the school dance."),
]
W[3] = [
("Basic","NatureHealingSwan","Nature Is Healing Swan","Relic","🦢","The swans came back. Nature is healing. We are the virus."),
("Basic","OnceAgainLectern","Once Again Asking Lectern","Relic","📋","I am once again asking for your support. And your snacks."),
("Basic","LockdownSourdough","Lockdown Sourdough Loaf","Relic","🍞","Everyone became a baker in 2020. This loaf survived."),
("Common","HeadBobCat","Head-Bob Vibe Cat","Statue","🐈","Bobbing its head to the beat since the dawn of time."),
("Common","PallbearerCoin","Pallbearer Dance Coin","Coin","⚰️","Struck to honor the dancing pallbearers. Astronomia plays when you flip it."),
("Common","TumbleJellyBean","Tumble Jelly Bean","Statue","🍬","Fell off every obstacle course ever made. Still smiling."),
("Uncommon","SwoleVsSmol","Swole Shiba vs Smol Shiba","Statue","💪","Back in my day we dug with our paws. Now: bonk."),
("Uncommon","PointingLaughChair","Pointing Laugh Armchair","Statue","📺","Pointing at the TV and laughing. Every human at every family gathering."),
("Uncommon","PolkaSpinCow","Polka Spin Cow","Statue","🐄","Spins to the same polka for eternity. Scientists can't stop it."),
("Rare","SusBean","Sus Space Bean","Statue","🔴","A tiny astronaut shaped like a bean. One of them was always acting sus."),
("Rare","PartyCornerGuy","They Don't Know Party Corner","Painting","🎉","Standing alone at the party, knowing something nobody else knows."),
("Rare","BeepBopMicKid","Beep-Bop Mic Kid","Statue","🎤","Won every rap battle with four arrows. Beep bop."),
("Epic","TradeOfferScroll","Trade Offer Scroll","Relic","📜","I receive: your meme. You receive: nothing. Deal?"),
("Epic","BigMittensChair","Big Mittens Folding Chair","Relic","🧤","A cozy pair of mittens on a folding chair. Photoshopped into every place on Earth."),
("Legendary","ThinkSonThink","Think, Son, Think! Hero","Statue","🦸","Shouted a question so loud it became a meme. Think!"),
("Legendary","SneakerShark","Three-Legged Sneaker Shark","Statue","🦈","A shark on three legs in blue sneakers. The face of Italian brainrot."),
("Godly","JawlineChad","Mega Jawline Chad","Statue","🗿","The most perfect jawline ever photographed, turned in the most dramatic direction."),
("Miracle","BingChillingCone","Bing Chilling Cone","Relic","🍦","Zao shang hao. The coldest ice cream in the lava trench."),
("Exotic","SigmaGrindset","Sigma Grindset Statue","Statue","🌅","Stares at the sunset alone. Refuses to have fun. Grinds."),
("Ruby","EmotionalDamage","Emotional Damage Heart","Relic","💔","Hit so hard it cracked. Emotional damage!"),
]
W[4] = [
("Basic","YesNoLabDog","Yes-No Lab Dog","Statue","🐶","Answers every question with yes, no, or a hang-up."),
("Basic","AssistantSam","Assistant Sam","Statue","📱","A phone assistant who became more famous than the phone."),
("Basic","LampOilMerchant","Lamp Oil Merchant","Statue","🛢️","Lamp oil, rope, bombs? You want it? It's yours, my friend."),
("Common","MaulingTimeVampire","It's Mauling Time Vampire","Statue","🦇","The film flopped. The meme earned a billion."),
("Common","GentlePillSquad","Gentle Yellow Pill Squad","Statue","🕶️","Went to the movies in suits. Very gentle. Very minion."),
("Common","WiseMysticalTree","Wise Mystical Tree","Statue","🌳","I am the wise mystical tree. Ask me anything."),
("Uncommon","ItsCornCob","It's Corn Cob","Relic","🌽","A big lump with knobs. It has the juice."),
("Uncommon","UncannySuperDad","Uncanny Super Dad","Painting","🖼️","The face gets darker the longer you look."),
("Uncommon","GirlDinnerPlate","Girl Dinner Plate","Relic","🧀","Bread, cheese, grapes, a pickle. Dinner is served."),
("Rare","PhonkEyebrowSpeaker","Phonk Eyebrow Speaker","Relic","🔊","Raises an eyebrow every time the bass drops."),
("Rare","RizzFaceMask","Rizz Face Mask","Relic","🤨","One eyebrow up, lips pressed. The rizz face, preserved forever."),
("Rare","ClangingPipe","Clanging Metal Pipe","Relic","🔩","The loudest sound effect in human history. CLANG."),
("Epic","BetterCallPaul","Better Call Paul Lawyer","Statue","⚖️","Did you know you have rights? This lawyer spins in 3D."),
("Epic","KingPrawnCrooner","King Prawn Crooner","Statue","🦐","A prawn in a pinstripe suit, singing his heart out."),
("Legendary","OhioFinalBoss","Ohio Final Boss","Statue","🌽","Only in Ohio. It wears a traffic cone as a crown."),
("Legendary","OhYeahVillain","Oh Yeah Orange-Suit Villain","Statue","🧡","Committed crimes with both direction and magnitude. OH YEAH!"),
("Eternal","LogBatGuy","Tung-Tung Log Guy","Statue","🏏","A wooden log with a baseball bat. It knocks three times before it arrives."),
("Supreme","ShailushaiCat","Shailushai Blue Cat","Statue","🍄","We live, we love, we lie. A blue cat walking the catacombs."),
("Insane","BirthdayShake","Sus Purple Birthday Shake","Relic","🥤","One sip and the humans in the video were never seen again."),
("Foresaken","WhistleEdit","Whistle Edit Relic","Relic","🎵","The whistle that played over a thousand edits of the same actor."),
]
W[5] = [
("Basic","PeachesTurtleKing","Peaches Piano Turtle King","Statue","🎹","Peaches, peaches, peaches. A turtle king's love song."),
("Basic","KindergartenMascot","Kindergarten Blob Mascot","Statue","🎈","The mascot of a kindergarten nobody should ever visit."),
("Basic","CursedCartoonTape","Cursed Cartoon Tape","Relic","📼","An old cartoon tape. Do not answer the questions it asks."),
("Common","AwkwardSmileGuy","Awkward Smile Guy","Statue","🙂","Smiled awkwardly in a hallway. Became immortal."),
("Common","LaughCryCarSeat","Laugh-Then-Cry Car Seat","Relic","🚘","Laughing one second, crying the next. The seat remembers."),
("Common","CanonEventWeb","Canon Event Web","Relic","🕸️","Some things have to happen. This web proves it."),
("Uncommon","PinkbombFeature","Pinkbomb Double Feature","Relic","🎬","Two movies, one weekend. Half pink, half boom."),
("Uncommon","BoulderEyebrow","The Boulder Eyebrow","Statue","🤨","A boulder that raised one eyebrow at humanity."),
("Uncommon","PointingSuits","Two Pointing Arachnid Suits","Statue","👉","Two identical heroes accusing each other of being the fake."),
("Rare","MewingHush","Mewing Hush Bust","Statue","🤫","Don't speak. You'll ruin the jawline. Bye bye."),
("Rare","EnglishSpanishChair","English or Spanish Chair","Relic","💺","English or Spanish? Choose wisely."),
("Rare","AHyuckDog","A-Hyuck Goofy Dog","Statue","🐕","Laughed so hard he became brainrot."),
("Epic","NoScopeOlympian","No-Scope Olympian","Statue","🎯","Won silver with one hand in his pocket. Didn't even try."),
("Epic","PommelHorseLegend","Pommel Horse Legend","Statue","🐎","Waited all day for one routine. Nailed it."),
("Legendary","BratGreenSlab","Brat Green Slab","Tablet","💚","A whole summer, carved in lime green."),
("Legendary","PedroRaccoon","Pedro Pedro Raccoon","Statue","🦝","Pedro, Pedro, Pedro. Spins forever."),
("Diabolical","CrocBomber","Crocodile Bomber Plane","Statue","🐊","A crocodile that is also a war plane. Nobody asked questions."),
("Celestial","ChillDude","Chill Dude in a Sweater","Statue","🐶","Hands in pockets, zero worries. Just a chill dude."),
("Unreal","BabyHippo","Bouncy Baby Hippo","Statue","🦛","A tiny wet hippo who bit everyone and was loved for it."),
("Forbidden","DubaiChocolate","Dubai Chocolate Bar","Relic","🍫","Snapped in half, oozing pistachio. The most expensive snack of 2025."),
]
W[6] = [
("Basic","LowTaperFade","Massive Low Taper Fade","Statue","💈","Imagine if this haircut was still trending. It's massive."),
("Basic","ShushUpTablet","Shush Up Tablet","Tablet","🤐","A stone tablet that tells everyone to be quiet."),
("Basic","BigGamerChair","Big Gamer Chair","Relic","🎮","The biggest gaming chair in the ocean. The snacks are gone."),
("Common","SixSevenHands","Six-Seven Hands","Statue","🙌","Six... seven. Palms up, one high, one low. 2025's word of the year."),
("Common","TakeEggCushion","Take Egg Cushion","Relic","🥚","Take egg. Just one egg. On a cushion."),
("Common","IbizaBossDancer","Ibiza Final Boss Dancer","Statue","🕺","The final boss of every beach party."),
("Uncommon","BoutiqueRock","Overpriced Boutique Rock","Relic","🏷️","A plain rock. $200. Sold out."),
("Uncommon","LittleFrenchFish","Steve the Little French Fish","Statue","🐟","Oui oui. A little fish with a big baguette."),
("Uncommon","VeryDemureTeacup","Very Demure Teacup","Relic","🍵","Very mindful. Very demure. Pinky out at all times."),
("Rare","JohnPorkPhone","John Pork Is Calling","Relic","📞","A pig in a suit is calling. Do not pick up."),
("Rare","BeforeGTA6Hourglass","Before-GTA6 Hourglass","Relic","⏳","Everything happened before the next big game came out. The sand is still falling."),
("Rare","StandingOnBusiness","Standing on Business Briefcase","Relic","💼","Literally standing on business."),
("Epic","AuraBoatBow","Aura Boat Bow","Relic","🚤","So much aura it glows. Farmed on a racing boat."),
("Epic","PaperclipHelper","Paperclip Helper","Statue","📎","It looks like you're digging up memes. Need help?"),
("Legendary","ZombieChickenRider","Baby Zombie Chicken Rider","Statue","🐔","The loudest cheer in any movie theater of the 2020s."),
("Legendary","JetTooHoliday","Jet Too Holiday Plane","Relic","✈️","Nothing beats a holiday. A cheerful little plane on its way to the sun."),
("Ascendent","PressureDiverHelmet","Deep Pressure Diver Helmet","Relic","🌊","Crushed by the deep. The bubbles still leak out."),
("Omega","AbyssalAngler","Abyssal Brainrot Angler","Statue","🐡","An anglerfish on three legs in sneakers, luring divers with a glowing brain."),
("Infinite","GlitchWhale","Oceanic Glitch Whale","Statue","🐋","A whale that failed to load. Half of it is still buffering."),
("Aquatic","AtlantisJawlineChad","Atlantis Jawline Chad","Statue","🔱","The jawline, lost at the bottom of the sea for a thousand years."),
]
W[7] = [
("Basic","SpookySkeleton","Spooky Scary Skeleton","Statue","💀","Sends shivers down your spine. Dances anyway."),
("Basic","PumpkinDancer","Pumpkin Head Dancer","Statue","🎃","A pumpkin-headed man who danced every October."),
("Basic","GhostlySwampFrog","Ghostly Swamp Frog","Statue","🐸","A frog under a sheet, haunting the swamp."),
("Common","BonkShiba","Bonk Shiba","Statue","🏏","Bonk. Go to meme jail."),
("Common","SadViolinHamster","Sad Violin Hamster","Statue","🐹","Big watery eyes and a tiny violin. Everyone cried."),
("Common","ConfusedMathCat","Confused Math Cat","Statue","🙀","Tried to understand the internet. Failed."),
("Uncommon","JellyTimeBanana","Jelly Time Banana","Statue","🍌","It's jelly time. A dancing banana from the early web."),
("Uncommon","RainbowPastryCat","Rainbow Pastry Cat","Statue","🌈","A cat made of frosted pastry, flying through space on a rainbow."),
("Uncommon","WowShiba","Much Wow Shiba","Statue","🐕","Such meme. Very classic. Wow."),
("Rare","ProblemGrinCoin","Problem Grin Coin","Coin","😏","A coin with a grin. Problem?"),
("Rare","MeLikeyTablet","Me Likey Tablet","Tablet","😌","A face that likes things a little too much."),
("Rare","RageScreamTablet","Rage Scream Tablet","Tablet","😡","Carved in pure rage."),
("Epic","ForeverAlone","Forever Alone Monument","Tablet","😢","A lonely stone face that every human secretly related to."),
("Epic","BadLuckBryan","Bad Luck Bryan Portrait","Painting","🍀","Took his driving test. Passed. Crashed into the building."),
("Legendary","FrowningCat","Frowning Cat Bust","Statue","😾","Never smiled once. Earned millions anyway."),
("Legendary","PunchMonkey","Punch & His Plushie","Statue","🐒","A baby monkey who never let go of his stuffed orangutan."),
("Ultimate","PhantomChonkyBunny","Phantom Chonky Bunny","Statue","👻","The biggest bunny ever came back as a ghost. Still big."),
("Beyond","CemeterySpecter","Cemetery Specter","Statue","🏮","A sheet ghost with a lantern, floating over the graves."),
("Immortal","UndeadSanic","Undead Sanic","Statue","🧟","Gotta go fast. Even after death."),
("Paradox","GraveyardOssuary","Graveyard Brainrot Ossuary","Statue","⚰️","The bones of brainrot past, standing in their own grave."),
]
W[8] = [
("Basic","CyberWowShiba","Cyber Much Wow Shiba","Statue","🤖","Such circuits. Very upgrade. Wow."),
("Basic","GlitchSwampFrog","Glitch Swamp Frog","Statue","🐸","A swamp frog split into two glitching copies."),
("Common","QuantumShockedRodent","Quantum Shocked Yellow Rodent","Statue","⚛️","Surprised in two universes at once."),
("Common","VoidStonks","Void Stonks Suit Head","Statue","📉","Stonks, but in the void. Up and down at the same time."),
("Uncommon","MultiverseSpaceInfant","Multiverse Space Infant","Statue","👶","Three green babies from three universes."),
("Uncommon","BulletDodgeGuy","Bullet-Dodge Code Guy","Statue","🕶️","Bent over backward. The bullets missed."),
("Rare","NeonSusBean","Neon Sus Space Bean","Statue","🔴","Glows when it's sus. Always glowing."),
("Rare","HoloJawlineChad","Holo Jawline Chad","Statue","🗿","The jawline as a hologram. Still sharper than you."),
("Epic","CosmicShake","Cosmic Purple Birthday Shake","Relic","🌌","A whole galaxy in a birthday milkshake."),
("Epic","SpacePolkaCow","Space Polka Cow","Statue","🐄","The polka cow, spinning on its own tiny planet."),
("Legendary","InterdimensionalChillDude","Interdimensional Chill Dude","Statue","🌀","Stepped through a portal. Still chill."),
("Legendary","CyberSingingThrone","Cyber Singing Throne","Statue","🚽","A chrome singing toilet with LED eyes."),
("Universal","UniversalSanic","Universal Sanic","Statue","🌠","A hedgehog made of stars. Gotta go fast across the universe."),
("Exponential","ExponentialOgre","Exponential Swamp Ogre","Statue","👹","An ogre with an ogre in its mouth, with an ogre in its mouth..."),
("Miraculous","MiraculousGnome","Miraculous Garden Gnome","Statue","🎅","You've been gnomed. Miraculously."),
("Apex","ApexWowShiba","Apex Much Wow Shiba","Statue","🏔️","The shiba at the top of the world. Very summit."),
("Gilded","GoldenSwampFrog","Golden Swamp Frog","Statue","🐸","A swamp frog cast in solid gold."),
("Toorng","ToorngEntity","Toorng Void Entity","Statue","👁️","A dark sphere covered in eyes. Nobody knows what Toorng means."),
("Roller","HighRollerBrainrot","High Roller Brainrot","Statue","🎲","The brainrot crew bet everything on double six."),
("Immeasupreme","ImmeasupremeOverlord","Immeasupreme Overlord","Statue","👑","The overlord of all memes, on a throne made of memes."),
]
W[9] = [
("Basic","QuantumDatFrog","Quantum Here Come Dat Frog","Statue","🐸","O shit waddup. A frog on a unicycle, in superposition."),
("Basic","SubatomicSwampFrog","Subatomic Swamp Frog","Statue","⚛️","A frog so small it's the center of an atom."),
("Basic","ParticleWowShiba","Particle Much Wow Shiba","Statue","✨","Such particles. Very small. Wow."),
("Common","AntimatterEchidna","Antimatter Red Echidna","Statue","🔵","Knows the anti-way."),
("Common","StringTheoryBunny","String Theory Chonky Bunny","Statue","🧶","A big bunny vibrating in eleven dimensions."),
("Common","WarpSpeedStonks","Warp Speed Stonks Head","Statue","🚀","Stonks at warp speed."),
("Uncommon","ParallelJawlineChad","Parallel Jawline Chad","Statue","👥","Two jawlines from two universes, back to back."),
("Uncommon","RealityWarpedSponge","Reality-Warped Porous Sponge","Statue","🌀","Heading out so fast he twisted reality."),
("Uncommon","TimeFoldPanels","Time Fold Nah-Yeah Panels","Tablet","🙅","Nah. Yeah. Folded through time."),
("Rare","DarkMatterHippo","Dark Matter Baby Hippo","Statue","🦛","A tiny hippo made of dark matter. Still bites."),
("Rare","RomanEmpireBust","Roman Empire Bust","Statue","🏛️","How often do you think about the Roman Empire? Every day."),
("Rare","HypercubeChillDude","Hypercube Chill Dude","Statue","🔷","Chilling in four dimensions."),
("Epic","ZeroPointThrone","Zero Point Singing Throne","Statue","🚽","A crystal singing toilet that floats on zero-point energy."),
("Epic","TesseractShake","Tesseract Birthday Shake","Relic","🥤","A birthday shake inside a four-dimensional cube."),
("Legendary","SingularityGrinCoin","Singularity Grin Coin","Coin","🕳️","The grin at the center of a black hole."),
("Legendary","EventHorizonShiba","Event Horizon Shiba","Statue","🌑","The shiba whose tail fell into a black hole."),
("Impossible","NeverGonnaStair","Never-Gonna Impossible Stair","Statue","🕺","Never gonna give up dancing on a staircase that never ends."),
("Quantum","QuantumBrainrotGod","Quantum Brainrot God","Statue","🔱","The six-armed god of all brainrot."),
("Transcendent","MemeMatrix","Transcendent Meme Matrix","Relic","💠","Every famous meme, suspended inside one crystal."),
("???","OriginalShiba","The Original Shiba","Statue","🌟","The good girl who started it all. Forever in our museum."),
]
