-- UIIconList (ModuleScript in ReplicatedStorage)
-- Written by tools/blender/ui_icons.py: the names of the 3D UI icons in assets/models/UIIcons.fbx.
-- Import that file once (File > Import 3D) and run the installer; UIKit.icon shows them.

return {
	"Shop",
	"Bag",
	"Museum",
	"Rebirth",
	"World",
	"Settings",
	"Gem",
	"Cash",
	"Income",
	"SoundOn",
	"SoundOff",
	"Music",
	"Bell",
	"Lock",
	"Luck",
	"Pickaxe",
	"Star",
	"Sparkle",
	"Heart",
	"Pin",
	"Alien",
	"Fire",
	"Skull",
	"Disk",
	"Volcano",
	"Candy",
	"Ghost",
	"Bubble",
	"Ice",
	"Snowflake",
	"Coin",
	"Warning",
	"Boom",
	"Party",
	"Picture",
	"Hole",
	"Elevator",
	"Crown",
	"FaceHappy",
	"FaceLaugh",
	"FaceLove",
	"FaceWow",
	"FaceCool",
	"FaceMeh",
	"FaceSick",
}
