# Meme captions for every artifact picture: id -> (top text, bottom text, extras)
# extras: "shades" (deal-with-it glasses), "crown", "sparkle", "fire", "tears", "rainbow",
#         "hearts", "halo", "motion", "bubble:<text>", "stars", "glitch", "sweat", "zzz", "100"
CAPTIONS = {
    # 1. The Scroll Pit
    "RustyFidgetSpinner": ("STILL SPINNING", "SINCE 2017", ["motion"]),
    "CrackedDancePhone": ("15 SECONDS", "ON LOOP FOREVER", ["glitch"]),
    "HalfFullBottle": ("BOTTLE FLIP", "NAILED IT", ["sparkle"]),
    "DeepFriedChip": ("DEEP FRIED", "EXTRA CRISPY", ["fire", "glitch"]),
    "SingingThrone": ("TOILET CONCERT", "DOP DOP YES YES", ["bubble:♪♪♪"]),
    "GoldenRingLight": ("RING LIGHT ON", "FACE FLAWLESS", ["sparkle", "halo"]),
    "RizzScroll": ("UNSPOKEN RIZZ", "LEVEL 100", ["sparkle", "100"]),
    "ScrollingThumb": ("JUST ONE MORE", "VIDEO", ["motion", "zzz"]),
    "MainCharacterCrown": ("ME WALKING IN", "LIKE THE MAIN CHARACTER", ["crown", "sparkle"]),
    "AlgorithmEye": ("THE ALGORITHM", "IS WATCHING", ["glitch"]),
    "FinalBrainrot": ("MY BRAIN", "AFTER 9 HOURS OF SCROLLING", ["fire", "glitch", "stars"]),
    # 2. Hashtag Hollow
    "HashtagSign": ("#BLESSED", "#NOFILTER #MEME", []),
    "EmptyIceBucket": ("ICE BUCKET", "CHALLENGE ACCEPTED", ["sweat"]),
    "MannequinStatue": ("MANNEQUIN CHALLENGE", "DON'T MOVE", ["bubble:...", "zzz"]),
    "ChallengeTrophy": ("WON THE CHALLENGE", "FORGOT WHICH ONE", ["sparkle"]),
    "ViralDanceStage": ("LEARNED THE DANCE", "IN 3 HOURS", ["motion", "stars"]),
    "TrendingCrown": ("TRENDING #1", "FOR EXACTLY 1 DAY", ["crown"]),
    "ChallengeScroll": ("EVERY CHALLENGE", "EVER. SO FAR.", ["sparkle"]),
    "HashtagConstellation": ("LOOK UP", "IT'S A HASHTAG", ["stars"]),
    "BrokeTheInternet": ("I BROKE", "THE INTERNET", ["glitch", "fire"]),
    # 3. Filter Fields
    "SelfieStick": ("BUT FIRST", "LET ME TAKE A SELFIE", ["sparkle"]),
    "PuppyEars": ("DOG FILTER", "ACTIVATED", ["hearts"]),
    "RainbowLens": ("LICK", "THE RAINBOW", ["rainbow"]),
    "PerfectMirror": ("FILTERED", "TO PERFECTION", ["sparkle"]),
    "SunsetCrystal": ("GOLDEN HOUR", "EVERY HOUR", ["sparkle"]),
    "FilterMask": ("WHICH FACE", "IS THE REAL ONE", ["glitch"]),
    "FirstSelfie": ("THE FIRST SELFIE", "NO FILTER. ICONIC.", ["halo"]),
    "AuroraPrism": ("#NOFILTER", "(FILTERED)", ["rainbow", "sparkle"]),
    "UnfilteredTruth": ("NO FILTER", "TOO POWERFUL", ["glitch", "sparkle"]),
    # 4. Emoji Quarry
    "ThumbsUpFossil": ("SEEN", "👍", []),
    "CryLaughStone": ("I'M CRYING", "IT'S NOT EVEN FUNNY", ["tears"]),
    "SkullRelic": ("I'M DEAD", "LITERALLY 💀", []),
    "FireTorch": ("THIS IS", "LIT", ["fire"]),
    "HeartEyesIdol": ("WHEN YOU SEE", "A CUTE DOG", ["hearts"]),
    "HundredTablet": ("KEEP IT", "ONE HUNDRED", ["100", "fire"]),
    "EmojiKeyboard": ("EVERY EMOJI", "EVEN THE WEIRD ONES", ["sparkle"]),
    "SparkleNebula": ("✨ AESTHETIC ✨", "VIBES ONLY", ["sparkle", "stars"]),
    "FirstSmiley": ("THE ORIGINAL", ":-)", ["halo"]),
    # 5. Algorithm Gorge
    "FeedFragment": ("THE FEED", "NEVER ENDS", ["motion"]),
    "RecommendedCard": ("RECOMMENDED", "FOR YOU", ["sparkle"]),
    "AutoplayClock": ("NEXT VIDEO IN 3", "... 2 ... 1", ["zzz"]),
    "SkipAdButton": ("SKIP AD", "IN 5 SECONDS", ["sweat"]),
    "EngagementEngine": ("LIKE, COMMENT", "AND SUBSCRIBE", ["motion"]),
    "ShadowbanCloak": ("SHADOWBANNED", "NOBODY SEES ME", ["glitch"]),
    "FeedOracle": ("I KNOW", "WHAT YOU'LL WATCH NEXT", ["sparkle", "stars"]),
    "NeuralChandelier": ("MACHINE LEARNING", "MACHINE MEMEING", ["glitch", "sparkle"]),
    "MasterAlgorithm": ("I AM", "THE ALGORITHM", ["glitch", "stars"]),
    # 6. Influencer Caverns
    "DiscountCoupon": ("USE MY CODE", "(EXPIRED)", []),
    "UnboxingBox": ("UNBOXING", "THE BOX", ["sparkle"]),
    "SponsoredDrink": ("THIS VIDEO", "IS SPONSORED", ["motion"]),
    "CheckmarkBadge": ("VERIFIED", "VERY IMPORTANT", ["sparkle"]),
    "MillionRing": ("1,000,000", "FOLLOWERS", ["sparkle", "100"]),
    "CollabKey": ("COLLAB", "HOUSE KEY", ["sparkle"]),
    "SubscriberPlaque": ("DIAMOND", "PLAY BUTTON", ["sparkle", "stars"]),
    "ViralAura": ("GOING VIRAL", "AURA +1000", ["halo", "sparkle"]),
    "FirstInfluencer": ("HEY GUYS", "WELCOME BACK", ["crown", "halo"]),
    # 7. Brainrot Abyss
    "NonsenseTablet": ("NONSENSE RIZZ", "GYATT OHIO", ["glitch"]),
    "SharkSneakers": ("SHARK", "IN SNEAKERS", ["motion"]),
    "SplitScreen": ("WATCH THIS", "WHILE YOU WATCH THIS", ["glitch"]),
    "RizzMeter": ("RIZZ LEVEL", "OVER 9000", ["fire", "100"]),
    "SigmaStatue": ("SIGMA", "GRINDSET", ["shades"]),
    "AuraVault": ("+1,000,000", "AURA POINTS", ["halo", "sparkle"]),
    "BrainrotCodex": ("THE BRAINROT", "DICTIONARY", ["glitch"]),
    "MewingMeteorite": ("MEWING", "JAWLINE UNLOCKED", ["stars", "shades"]),
    "BrainrotFinalBoss": ("FINAL BOSS", "OF BRAINROT", ["fire", "glitch", "crown"]),
    # 8. Rage Comic Ridge
    "FlipPhone": ("ONE BAR", "OF SIGNAL", ["sweat"]),
    "AngryDoodle": ("FFFFUUUU", "UUUUUUU", ["fire"]),
    "DentedAirhorn": ("PRO GAMER", "AIRHORN", ["motion"]),
    "PixelSunglasses": ("DEAL", "WITH IT", ["shades"]),
    "CatCassette": ("CAT VIDEOS", "VOL. 1", ["sparkle"]),
    "SacredPlank": ("THE PLANK", "IS SACRED", ["halo"]),
    "TrickshotHeadset": ("360 NO SCOPE", "GET REKT", ["shades", "motion"]),
    "ForeverAlone": ("FOREVER", "ALONE", ["tears"]),
    "ChallengeBanner": ("CHALLENGE", "ACCEPTED", ["sparkle"]),
    "GrinningMoon": ("PROBLEM?", "U MAD BRO", ["shades"]),
    "OriginalFourPanel": ("THE ORIGINAL", "FOUR-PANEL COMIC", ["halo"]),
    # 9. Montage Mines
    "HeadsetMic": ("1V1 ME", "BRO", ["bubble:GG"]),
    "SodaPyramid": ("GAMER FUEL", "LEVEL 99", ["motion"]),
    "HitmarkerPin": ("HITMARKER", "HITMARKER", ["glitch"]),
    "DubstepSpeaker": ("WUB WUB", "WUB WUB WUB", ["motion"]),
    "TriangleChipCrown": ("PRO GAMER", "SNACK KING", ["crown", "shades"]),
    "AllSeeingTriangle": ("ILLUMINATI", "CONFIRMED", ["glitch", "stars"]),
    "QuickscopeRelic": ("QUICKSCOPED", "GET REKT", ["shades", "motion"]),
    "LensFlareStar": ("LENS FLARE", "EVERYWHERE", ["sparkle", "stars"]),
    "UltimateMontage": ("THE ULTIMATE", "PRO MONTAGE", ["shades", "fire"]),
    # 10. Cat Video Canyon
    "LaserDot": ("RED DOT", "MUST CATCH", ["motion"]),
    "CatInBox": ("IF I FITS", "I SITS", ["hearts"]),
    "FrowningCat": ("I HAD FUN", "ONCE. IT WAS AWFUL.", []),
    "PianoKitten": ("PLAY HIM OFF", "KITTEN", ["bubble:♪♫"]),
    "ToastCatMachine": ("TOAST CAT", "NYA NYA NYA", ["rainbow", "stars"]),
    "CatVideoHall": ("1,000 CAT VIDEOS", "WATCHED TODAY", ["hearts"]),
    "TableCat": ("*PUSHES CUP*", "*MAINTAINS EYE CONTACT*", []),
    "LoafNebula": ("CAT LOAF", "PERFECT BREAD", ["stars", "hearts"]),
    "FirstInternetCat": ("I CAN HAS", "CHEEZBURGER?", ["halo"]),
    # 11. Airhorn Crater
    "CrackedSoundboard": ("PRESS BUTTON", "FOR MEME", ["motion"]),
    "SadTrombone": ("WAH", "WAH WAAAH", ["tears"]),
    "DramaticHamster": ("DUN", "DUN DUNNN", ["motion"]),
    "BassDetonator": ("WAIT FOR IT", "...DROP", ["fire", "motion"]),
    "GoldenAirhorn": ("BWAAAAMP", "BWAAAAAAMP", ["motion", "sparkle"]),
    "Volume100Amp": ("VOLUME", "100%", ["100", "motion"]),
    "FanfareOrgan": ("VICTORY", "ROYALE", ["sparkle", "crown"]),
    "SonicBoomComet": ("GOTTA GO", "FAST", ["motion", "fire"]),
    "FirstSoundMeme": ("THE FIRST", "SOUND MEME", ["halo", "bubble:♪"]),
    # 12. Planking Plateau
    "OwlingPerch": ("OWLING", "NEW TREND", []),
    "DuckFaceMirror": ("DUCK FACE", "SO CUTE", ["sparkle"]),
    "PhotobombCutout": ("PHOTOBOMB", "GOT YOU", ["motion"]),
    "DancePartyHelmet": ("SUDDEN", "DANCE PARTY", ["stars", "motion"]),
    "DoubleRainbowPrism": ("DOUBLE RAINBOW", "WHAT DOES IT MEAN", ["tears", "sparkle"]),
    "TableTower": ("PLANKING", "ON EVERYTHING", []),
    "InvisibleHorseSaddle": ("INVISIBLE", "HORSE DANCE", ["motion"]),
    "PlankConstellation": ("EVEN THE STARS", "ARE PLANKING", ["stars"]),
    "OriginalPlank": ("THE ORIGINAL", "PLANK", ["halo"]),
    # 13. Viral Valley
    "ForwardedJoke": ("FWD: FWD: FWD:", "FUNNY!!!", []),
    "CryptidPhoto": ("DEFINITELY REAL", "100% NOT BLURRY", ["glitch"]),
    "LoopingGif": ("THIS GIF", "NEVER ENDS", ["motion"]),
    "BittenBandage": ("CHARLIE", "BIT MY FINGER", ["tears"]),
    "WeekendCalendar": ("IT'S FRIDAY", "FRIDAY", ["sparkle"]),
    "SuperfanTear": ("LEAVE THEM", "ALONE!!!", ["tears"]),
    "MillionViewTrophy": ("1 MILLION", "VIEWS", ["sparkle", "100"]),
    "ShareSupernova": ("SHARE", "IF YOU AGREE", ["stars", "sparkle"]),
    "PatientZeroVideo": ("THE VIDEO", "THAT WENT VIRAL", ["glitch"]),
    # 14. The Golden Server
    "OverheatedDrive": ("TOO MANY MEMES", "SYSTEM OVERHEATING", ["fire", "sweat"]),
    "BlinkingLight": ("SERVER", "NOT RESPONDING", ["glitch"]),
    "ModBadge": ("THREAD", "LOCKED", ["shades"]),
    "FirstCommentPlaque": ("FIRST!", "(NOBODY CARES)", ["crown"]),
    "GoldenUpvote": ("TAKE MY", "UPVOTE", ["sparkle"]),
    "ServerThrone": ("KING", "OF THE SERVER", ["crown"]),
    "LostThreadsArchive": ("THREAD", "NOT FOUND", ["glitch"]),
    "ActualCloud": ("SAVED TO", "THE CLOUD", ["sparkle"]),
    "GoldenServerCore": ("THE CORE", "OF ALL MEMES", ["sparkle", "stars"]),
    # 15. Dial-Up Dunes
    "FloppyDisk": ("1.44 MB", "OF MEMES", []),
    "DialUpModem": ("EEEEE", "KSHHHHH BEEP", ["motion"]),
    "ConstructionSign": ("UNDER", "CONSTRUCTION", ["glitch"]),
    "HitCounter": ("YOU ARE", "VISITOR #000042", ["sparkle"]),
    "ChainEmail": ("SEND TO 10 FRIENDS", "OR ELSE", ["fire"]),
    "PixelPet": ("FEED ME", "OR I PERISH", ["hearts"]),
    "EmoticonStone": (":-)", "THE ANCIENT FACE", ["halo"]),
    "GoldenModem": ("56K", "BLAZING FAST", ["motion", "sparkle"]),
    "OriginalHomepage": ("WELCOME TO", "MY HOMEPAGE", ["sparkle"]),
    "HandshakeComet": ("CONNECTING", "PLEASE WAIT", ["stars", "motion"]),
    "FirstConnection": ("YOU'VE GOT", "MAIL", ["sparkle"]),
    # 16. Pixel Pits
    "DeadPixel": ("ONE DEAD PIXEL", "CAN'T UNSEE IT", ["glitch"]),
    "PixelHeart": ("EXTRA LIFE", "+1", ["hearts"]),
    "Spinning3DLogo": ("SPINNING", "3D TEXT", ["motion"]),
    "HeroSprite": ("IT'S DANGEROUS", "TO GO ALONE", ["sparkle"]),
    "CoinSlot": ("INSERT COIN", "TO CONTINUE", ["sparkle"]),
    "LowPolyCrown": ("KING OF", "LOW POLY", ["crown"]),
    "CursorIdol": ("CLICK", "HERE", ["sparkle"]),
    "PixelGalaxy": ("8-BIT", "GALAXY", ["stars"]),
    "FirstPixel": ("THE FIRST", "PIXEL", ["halo", "sparkle"]),
    # 17. Guestbook Graveyard
    "UnsignedGuestbook": ("SIGN MY", "GUESTBOOK", []),
    "FlameDivider": ("COOL SITE", "IS COOL", ["fire"]),
    "WebringChain": ("NEXT SITE", "IN THE WEBRING", ["motion"]),
    "MidiMusicBox": ("AUTOPLAY MIDI", "YOU'RE WELCOME", ["bubble:♪♫♪"]),
    "MarqueeScroll": ("SCROLLING TEXT", "SCROLLING TEXT", ["motion"]),
    "NotFoundTombstone": ("404", "PAGE NOT FOUND", ["halo"]),
    "MillionthVisitor": ("CONGRATULATIONS", "YOU WON!!!", ["sparkle", "stars"]),
    "PopupAurora": ("CLOSE ONE", "3 MORE APPEAR", ["glitch"]),
    "LastSignature": ("LAST SEEN", "1999", ["tears"]),
    # 18. Floppy Fossil Beds
    "MouseBallFossil": ("CLEAN", "THE MOUSE BALL", ["sweat"]),
    "CDRomShard": ("INSERT", "DISC 2", ["sparkle"]),
    "TangledCable": ("UNTANGLING", "SINCE 1998", ["sweat"]),
    "AssistantFossil": ("IT LOOKS LIKE", "YOU'RE DIGGING", ["bubble:?"]),
    "BeigeTower": ("BEIGE", "IS BEAUTIFUL", ["sparkle"]),
    "BurnedMixCD": ("MY MIX CD", "BANGERS ONLY", ["fire"]),
    "ScreensaverPipes": ("PIPES", "FOREVER", ["motion"]),
    "SaveConstellation": ("DON'T FORGET", "TO SAVE", ["stars"]),
    "OriginalSaveIcon": ("THE SAVE ICON", "WHAT IS A FLOPPY", ["halo"]),
    # 19. The Homepage Ruins
    "BrokenHyperlink": ("CLICK HERE", "LINK BROKEN", ["glitch"]),
    "SpinningGlobe": ("WORLD WIDE", "WEB", ["motion"]),
    "ComicFontTablet": ("COMIC SANS", "IS BACK", ["sparkle"]),
    "GlitterCrown": ("GLITTER TEXT", "IS ART", ["sparkle", "crown"]),
    "TiledMosaic": ("TILED", "BACKGROUND", ["glitch"]),
    "FrameThrone": ("RULER", "OF FRAMES", ["crown"]),
    "HandCodedTablet": ("<HTML>", "BY HAND", ["sparkle"]),
    "HitCounterGalaxy": ("VISITORS:", "12", ["stars"]),
    "HomepageOfHomepages": ("THE FIRST", "HOMEPAGE", ["halo", "crown"]),
    # 20. The First Server
    "AncientEthernet": ("PLUG IT IN", "IT'S THE INTERNET", ["sparkle"]),
    "CommandLineRune": ("C:\\>", "DIR MEMES", ["glitch"]),
    "FirstEmail": ("SUBJECT:", "TEST", ["halo"]),
    "PrimordialSpam": ("YOU WON", "A FREE PRIZE!!!", ["sparkle"]),
    "FirstMemeStone": ("THE FIRST", "MEME EVER", ["halo", "sparkle"]),
    "ServerHeart": ("THE INTERNET", "IS ALIVE", ["hearts"]),
    "CreationHyperlink": ("THE FIRST", "LINK", ["halo", "stars"]),
    "ActualWeb": ("WORLD WIDE WEB", "(LITERALLY)", ["stars"]),
    "InternetSourceCode": ("THE SOURCE CODE", "OF EVERYTHING", ["glitch", "halo"]),
    # 21. The Abyss (secret 2050 memes)
    "LastHumanMeme": ("THE LAST MEME", "MADE BY A HUMAN", ["tears", "halo"]),
    "AIGirlfriendFirmware": ("I UNDERSTAND", "HOW YOU FEEL", ["hearts", "glitch"]),
    "BrainrotCoreSample": ("FROZEN BRAINROT", "HANDLE WITH CARE", ["sparkle"]),
    "SkibidiMonolith": ("OHIO", "IS WATCHING", ["glitch", "stars"]),
    "FinalUpvote": ("THE LAST", "UPVOTE EVER", ["halo", "sparkle"]),
    "QuantumDoge": ("SUCH QUANTUM", "VERY BOTH. WOW", ["sparkle", "stars"]),
    "MemeSingularity": ("THE MEME", "IS LOOKING AT YOU", ["glitch", "stars"]),
    "SourceOfIrony": ("UNIRONICALLY", "IRONIC", ["glitch", "halo"]),
    # Parody meme figures
    "ChillDude": ("JUST A", "CHILL DUDE", []),
    "ChillDudeTablet": ("CHILL SINCE", "THE STONE AGE", []),
    "ShockedRodent": ("WHEN THE CONSEQUENCES", "ARRIVE", ["sweat"]),
    "PurpleBirthdayShake": ("HAPPY BIRTHDAY", "(SUS)", ["glitch"]),
    "SpaceInfant": ("TINY", "BUT MIGHTY", ["hearts"]),
    "LogBatGuy": ("TUNG TUNG TUNG", "KNOCK KNOCK", ["motion"]),
    "CappuccinoBallerina": ("ONE ESPRESSO", "PIROUETTE", ["sparkle"]),
    "CrocBomber": ("CROCODILE", "AIR FORCE", ["motion"]),
    "JawlineChad": ("AVERAGE", "JAWLINE ENJOYER", ["sparkle"]),
    "SpongeLeaving": ("AIGHT", "I'M HEADING OUT", ["motion"]),
    "PurpleTitanBuggy": ("INEVITABLE", "BUT COMPACT", []),
    "RainbowPastryCat": ("NYA NYA", "NYA NYA", ["rainbow", "stars"]),
    "SusBean": ("THAT'S", "KINDA SUS", ["glitch"]),
    "ChonkyBunny": ("BIG", "CHONK", []),
    "FineDog": ("THIS IS", "FINE", ["fire"]),
    "PointingSuits": ("NO YOU'RE", "THE FAKE", []),
    "WowShibaCoin": ("SUCH COIN", "VERY WOW", ["sparkle"]),
}
